title: OMNIS
description: Optical Mesoscale Neural Interrogation System
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: https://a-rouxel.github.io
baseurl: /OMNIS-website

search_enabled: true
color_scheme: light

aux_links:
  "GitHub":
    - "https://github.com/a-rouxel/OMNIS-website"
